### Patricia Aguado Labrador

Discretización de atributos.

In [1]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score as ac
from sklearn.metrics import confusion_matrix

In [2]:
data = pd.read_csv('ThoraricSurgery.csv')
data

,DGN,PRE4,PRE5,PRE6,PRE7,PRE8,PRE9,PRE10,PRE11,PRE14,PRE17,PRE19,PRE25,PRE30,PRE32,AGE,Risk1Yr
0,DGN2,2.88,2.16,PRZ1,F,F,F,T,T,OC14,F,F,F,T,F,60,F
1,DGN3,3.40,1.88,PRZ0,F,F,F,F,F,OC12,F,F,F,T,F,51,F
2,DGN3,2.76,2.08,PRZ1,F,F,F,T,F,OC11,F,F,F,T,F,59,F
3,DGN3,3.68,3.04,PRZ0,F,F,F,F,F,OC11,F,F,F,F,F,54,F
4,DGN3,2.44,0.96,PRZ2,F,T,F,T,T,OC11,F,F,F,T,F,73,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,DGN2,3.88,2.12,PRZ1,F,F,F,T,F,OC13,F,F,F,T,F,63,F
466,DGN3,3.76,3.12,PRZ0,F,F,F,F,F,OC11,F,F,F,T,F,61,F
467,DGN3,3.04,2.08,PRZ1,F,F,F,T,F,OC13,F,F,F,F,F,52,F
468,DGN3,1.96,1.68,PRZ1,F,F,F,T,T,OC12,F,F,F,T,F,79,F
469,DGN3,4.72,3.56,PRZ0,F,F,F,F,F,OC12,F,F,F,T,F,51,F

In [3]:
def discretize(data, column, interval):
    data_column = data[:,column]
    
    for d in range(len(data_column)):
        value = data_column[d]

        for i in range(len(interval[0])-1,-1,-1):
            
            if (value <= interval[0][i]):
                data_column[d] = interval[1][i]
                
            elif(interval[0][i] == interval[0][-1]):
                data_column[d] = interval[1][-1]
                
    data[:,column] = data_column
    return data

In [4]:
data1 = np.asarray(data)
columns = [15,1,2]

intervals = [[[62,65,70],['62 o menos','De 63 a 65','De 66 a 70','Más de 70']],
            [[2.66,2.88],['2.66 o menos','De 2.67 a 2.88','Más de 2.88']],
            [[2.04],['2.04 o menos','Más de 2.04']]]

In [5]:
for i in range(len(columns)):
    data = discretize(data1, columns[i], intervals[i])
print(data)

[['DGN2' 'De 2.67 a 2.88' 'Más de 2.04' ... 'F' '62 o menos' 'F']
 ['DGN3' 'Más de 2.88' '2.04 o menos' ... 'F' '62 o menos' 'F']
 ['DGN3' 'De 2.67 a 2.88' 'Más de 2.04' ... 'F' '62 o menos' 'F']
 ...
 ['DGN3' 'Más de 2.88' 'Más de 2.04' ... 'F' '62 o menos' 'F']
 ['DGN3' '2.66 o menos' '2.04 o menos' ... 'F' 'Más de 70' 'F']
 ['DGN3' 'Más de 2.88' 'Más de 2.04' ... 'F' '62 o menos' 'F']]

In [6]:
output = pd.DataFrame(data1, columns= ['DGN', 'PRE4', 'PRE5', 'PRE6', 'PRE7', 'PRE8', 'PRE9', 'PRE10', 'PRE11',
       'PRE14', 'PRE17', 'PRE19', 'PRE25', 'PRE30', 'PRE32', 'AGE', 'Risk1Yr'])
output.to_csv ('/home/patricia/Desktop/SEGUNDO CUATRIMESTRE/TAA/LAB/P3/discretizado.csv', index = False, header=True)