# Entrega 2. ID3

### Patricia Aguado Labrador

In [1]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score as ac
from sklearn.metrics import confusion_matrix

In [2]:
data = pd.read_csv('funcion.csv')
data

    A  B  C  D  E  CLASE
0   0  0  0  0  0      1
1   0  0  0  0  1      0
2   0  0  0  1  0      0
3   0  0  0  1  1      1
4   0  0  1  0  0      0
5   0  0  1  0  1      1
6   0  0  1  1  0      0
7   0  0  1  1  1      1
8   0  1  0  0  0      1
9   0  1  0  0  1      0
10  0  1  0  1  0      0
11  0  1  0  1  1      1
12  0  1  1  0  0      0
13  0  1  1  0  1      1
14  0  1  1  1  0      0
15  0  1  1  1  1      1
16  1  0  0  0  0      1
17  1  0  0  0  1      0
18  1  0  0  1  0      0
19  1  0  0  1  1      1
20  1  0  1  0  0      0
21  1  0  1  0  1      1
22  1  0  1  1  0      0
23  1  0  1  1  1      1
24  1  1  0  0  0      1
25  1  1  0  0  1      0
26  1  1  0  1  0      1
27  1  1  0  1  1      0
28  1  1  1  0  0      1
29  1  1  1  0  1      0
30  1  1  1  1  0      1
31  1  1  1  1  1      0

In [3]:
data_feature_names = np.asarray(data.columns)
data_feature_names = np.delete(data_feature_names,-1)

data = np.asarray(data)
print(data)
data_class_names = np.unique(data[:,-1])
data_class_names = data_class_names.astype(str)

[[0 0 0 0 0 1]
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 1 1 1]
 [0 0 1 0 0 0]
 [0 0 1 0 1 1]
 [0 0 1 1 0 0]
 [0 0 1 1 1 1]
 [0 1 0 0 0 1]
 [0 1 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 0 1 1 1]
 [0 1 1 0 0 0]
 [0 1 1 0 1 1]
 [0 1 1 1 0 0]
 [0 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 1 0]
 [1 0 0 1 0 0]
 [1 0 0 1 1 1]
 [1 0 1 0 0 0]
 [1 0 1 0 1 1]
 [1 0 1 1 0 0]
 [1 0 1 1 1 1]
 [1 1 0 0 0 1]
 [1 1 0 0 1 0]
 [1 1 0 1 0 1]
 [1 1 0 1 1 0]
 [1 1 1 0 0 1]
 [1 1 1 0 1 0]
 [1 1 1 1 0 1]
 [1 1 1 1 1 0]]

In [4]:
X_train = data[:,:5]
y_train = data[:,-1]

In [5]:
clf = DecisionTreeClassifier(random_state=0, criterion = 'entropy')
clf = clf.fit(X_train, y_train)

predicted = clf.predict(X_train)
ac = ac(predicted,y_train)

print("\n\33[4mTasa de acierto:\33[0m ",ac)

Tasa de acierto:  1.0

In [6]:
error_rate = (1-ac)*100
print("\n\33[4mPorcentaje de ejemplos mal clasificados:\33[0m ",error_rate,"%")

Porcentaje de ejemplos mal clasificados:  0.0 %

In [7]:
cm = confusion_matrix(y_train, predicted)
print("\n\33[4mMatriz de confusión:\33[0m\n")
for i in cm:
    print("    ",i)
print("\n")

Matriz de confusión:

     [16  0]
     [ 0 16]

In [8]:
export_graphviz(clf, out_file='treeID3.dot', feature_names = data_feature_names, class_names = data_class_names, filled = True)
!dot -Tpng treeID3.dot -o treeID3.png -Gdpi=600